name: CI/CD Pipeline

on:
  push:
    branches: 
      - main

jobs:
  install_and_build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.9

    - name: Print masked environment variable (just length for test)
      env:
        HUGGINGFACEHUB_API_TOKEN: ${{ secrets.HUGGINGFACEHUB_API_TOKEN }}
      run: |
        echo "✅ Hugging Face Token is set."
        echo "Token length: ${#HUGGINGFACEHUB_API_TOKEN}"
        
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/workout-app:latest .

    # Optional: Push to Docker Hub (if you want it stored there)
    - name: Push Docker image
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/workout-app:latest
